version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8.12'

    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v3-npm-cache-{{ checksum "package-lock.json" }}'

      - run: npm install

      - run:
          name: update webdriver
          command: npm run e2e:update
          background: true

      - run:
          name: start webdriver
          command: npm run start:chrome
          background: true

      - run: npm run docs

      - store_artifacts: docs/index.html

      - run: npm test
